cabinet/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from .views import MessageListView, MessageCreateView, \
    MessageDialogListView, DeleteDialogView, DeleteMessageView, DeleteAccount

urlpatterns = patterns('cabinet.views',
    url(r'^$', 'view', name="view"),
    url(r'^edit/$', 'profile_edit', name='edit'),
    url(r'^drafts/$', 'drafts', name="drafts"),
    url(r'^draft/(?P<pk>\d+)/$', 'draft_edit', name='draft_edit'),
    url(r'^draft/(?P<pk>\d+)/delete/$', 'draft_delete', name='draft_delete'),
    url(r'^adverts/$', 'adverts', name="adverts"),
    url(r'^events/$', 'events', name='events'),
    url(r'^archive/$', 'events_archive', name='archive'),
    url(r'^comments/$', 'comments_list', name='comments'),
    url(r'^messages/$', MessageListView.as_view(), name='messages'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/$', MessageDialogListView.as_view(), name='dialog'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/delete/$', DeleteDialogView.as_view(), name='dialog_delete'),
    url(r'^messages/(?P<pk>\d+)/delete/$', DeleteMessageView.as_view(), name='message_delete'),
    url(r'^message/new/$', MessageCreateView.as_view(), name='message_new'),
    url(r'^delete/$', DeleteAccount.as_view(), name='delete_account'),

    # url(r'^draft/(?P<pk>\d+)/$', 'draft_view', name="draft_view"),
    # url(r'^(?P<pk>\d+)/$', 'get_profile', name='view'),
)

catalog/urls.py
from django.conf.urls import patterns, url
from .models import Advert

urlpatterns = patterns('catalog.views',
    url(r'^market/$', 'flea_market', name='market'),
    url(r'^view/(?P<pk>\d+)/$', 'advert_detail', name='advert_detail'),
    url(r'^edit/(?P<pk>\d+)/$', 'advert_edit', name='advert_edit'),
    url(r'^delete/(?P<pk>\d+)/$', 'advert_delete', name='advert_delete'),
    url(r'^notactual/(?P<pk>\d+)/$', 'advert_notactual', name='advert_notactual'),
    url(r'^add/new/$', 'advert_new', name='new'),
    
    url(r'^add/(?P<pk>\d+)/$', 'advert_add', name='add'),

    url(r'^img/(?P<pk>\d+)/$', 'img_add', {'model': Advert}, name='img_add'),
    url(r'^img_url/(?P<pk>\d+)/$', 'img_url_add', {'model': Advert}, name='img_url_add'),
    url(r'^img/(?P<pk>\d+)-(?P<image_pk>\d+)/(?P<action>delete|cover)/$',
        'img_control', {'model': Advert}, name='img_control'),

    url(r'^(?P<slug>[\w-]+)/$', 'catalog_detail', name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$', 'category_detail', name='category_detail'),

)

event/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from event.views import EventListView, EventCreateView, EventDetailView, \
    EventEditView, EventUpView, CommitAddView, CommentPageView, \
    EventUploadView, EventUploadUrlView, EventUploadDeleteView, EventDeleteView
from core.views import event_make_like
from .models import Event

urlpatterns = patterns('',
    url(r'^$', EventListView.as_view(), name='list'),
    url(r'^events/add/$', EventCreateView.as_view(), name='create'),
    url(r'^events/(?P<pk>\d+)/$', EventDetailView.as_view(), name='detail'),
    url(r'^events/(?P<pk>\d+)/edit/$', EventEditView.as_view(), name='edit'),
    url(r'^events/(?P<pk>\d+)/edit/(?P<key>\w+)', EventEditView.as_view(),
        name='edit_for_key'),
    url(r'^events/(?P<pk>\d+)/up/$', EventUpView.as_view(), name='up'),
    url(r'^events/(?P<pk>\d+)/comment/add/$', CommitAddView.as_view(),
        name='comment_add'),
    url(r'^events/(?P<pk>\d+)/comment/$', CommentPageView.as_view(),
        name='comment_page'),

    url(r'^events/upload/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadView.as_view(), name='upload'),

    url(r'^events/upload_from_url/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadUrlView, name='upload_from_url'),

    url(r'^events/upload/del/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadDeleteView.as_view(), name='upload_del'),
    url(r'^events/delete/(?P<pk>\d+)/$',
        EventDeleteView.as_view(), name='delete'),

    url(r'^events/(?P<pk>\d+)/(?P<kind>["like"|"dislike"]+)/$', event_make_like, name='like'),
    # url(r'^events/(?P<pk>\d+)//$', event_make_dislike, name='dislike'),

    url(r'^events/img/(?P<pk>\d+)/$', 'catalog.views.img_add',
        {'model': Event}, name='img_add'),
    url(r'^events/img_url/(?P<pk>\d+)/$', 'catalog.views.img_url_add',
        {'model': Event}, name='img_url_add'),
    url(r'^events/img/(?P<pk>\d+)-(?P<image_pk>\d+)/(?P<action>delete|cover)/$',
        'catalog.views.img_control', {'model': Event}, name='img_control'),
)

infoportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.conf import settings
from event.views import EventListView
# from django_geoip.views import set_location

admin.autodiscover()

urlpatterns = patterns('',
    # home
    url(r'^$', EventListView.as_view(), name='home'),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^', include('registration.urls')),

    # for menu order
    # url(r'^pagesorter/orderedmove_order/(?P<direction>up|down)/(?P<model_type_id>\d+)/(?P<model_id>\d+)/$',
    #      'core.views.admin_move_ordered_model_order',
    #      name="admin_move_order"),

    # other apps
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
    url(r'^', include('event.urls', 'event')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # url(r'^article/', include('core.urls', namespace='core')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # geo
    url(r'^geo/regions/$', 'core.views.get_regions', name='get_regions'),
    url(r'^geo/region-(?P<region_pk>\d+)/$', 'core.views.get_cities', name='get_cities'),
    url(r'^geo/city/autocomplete/$', 'core.views.city_autocomplete', name='city_autocomplete'),
    # url(r'^geoip/', include('django_geoip.urls')),
    # url(r'^geoip/setlocation/', 'core.views.set_location', name='geoip_change_location'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('search.urls')),
    url(r'^', include('catalog.urls', app_name="catalog", namespace='catalog')),
    url(r'^', include('event.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/forms.py
from django import forms


class GeoForm(forms.Form):
    geo_city = forms.CharField()
    # city_id = forms.CharField(widget=forms.HiddenInput())

    # region = forms.ModelChoiceField(queryset=[], empty_label="---------")
    # city = forms.ModelChoiceField(queryset=[], empty_label="---------")
    # def __init__(self, *args, **kwargs):
        # c = kwargs.pop('c')
        # super(GeoForm, self).__init__(*args, **kwargs)
        # self.fields['region'].queryset = c['regions']
        # self.fields['city'].queryset = c['cities']

templates/templatetags/banner.html
{% if banner %}
    <div class="banner">
        <ul>
            {% for item in banner %}
                {% if item.is_swf %}
                    <li class="item">
                        <object>
                            <param name="movie" value="{{ item.url }}">
                            <param name="quality" value="best">
                            <param name="wmode" value="opaque">
                            <embed src="{{ item.file.url }}" quality="best" wmode="opaque" type="application/x-shockwave-flash" width="330" height="90">
                        </object>
                        {% else %}
                    <li class="item"><a href="{{ item.url }}" target="{{ item.target }}"><img src="{{ item.file.url }}" alt="{{ item.url }}"/></a>
                {% endif %}
            {% endfor %}
        </ul>
    </div>
{% endif %}

templates/templatetags/cabinet_menu.html
<div class="category_block">
    <header>Ссылки</header>
    <div class="profile_links">
        <a href="{% url 'cabinet:view' %}">Личный кабинет</a>
        <a href="{% url 'cabinet:messages' %}">Мои сообщения ({{ quantity.messages|default:'0' }})
            <span class="new_message">{% firstof quantity.messages_new '' %}</span></a>
        <a href="{% url 'cabinet:adverts' %}">Мои объявления ({{ quantity.adverts|default:'0' }})</a>
        <a href="{% url 'cabinet:drafts' %}">Мои черновики ({{ quantity.drafts|default:'0' }})</a>
        <a href="{% url 'cabinet:events' %}">Мои ивенты ({{ quantity.events|default:'0' }})</a>
        <a href="{% url 'cabinet:archive' %}">Архив ({{ quantity.archive|default:'0' }})</a>
        <a href="{% url 'cabinet:comments' %}">Мои комментарии ({{ quantity.comments|default:'0' }})</a>
        <a href="{% url 'cabinet:edit' %}">Редактирование профиля</a>
    </div>
</div>

templates/templatetags/cat_menu.html
{% if cat_menu %}
    {% for catalog in cat_menu %}
        <li>
            {% if catalog.count and catalog.count != 0 %}
                <span>
                    {{ catalog.count }}
                </span>
            {% endif %}
            {% if catalog.categories %}
                <i class="fa fa-plus-circle"></i>
            {% endif %}
            <a href="{% url 'catalog:detail' catalog.slug %}">
                {{ catalog.title }}
            </a>
            {% if catalog.categories %}
                <ul>
                    {% for category in catalog.categories %}
                        <li><a href="{% url 'catalog:category_detail' category.slug %}">
                            {{ category.title }}
                        </a></li>
                    {% endfor %}
                </ul>
            {% endif %}
        </li>
    {% endfor %}
{% endif %}

templates/templatetags/geo_menu.html
{% load static %}
{% load widget_tweaks %}

<form action="" method="post" id="add" class="geo_form">
    {% csrf_token %}
    <fieldset>
        <label for="id_geo_city">Город</label>
        {{ form.geo_city }}
        <br/>
        <div class="wrap_no_city">
            <span class='no_city'></span>
        </div>
    </fieldset>
    <br/>
    <input type="submit" value="Сохранить" class="save_cookie">
    <a href="#" class="cookie_cancel">Отмена</a>
</form>

templates/templatetags/latest.html
{% load thumbnail staticfiles core_tags %}
<div class="category_block">
    <header>Свежие</header>

{% for advert in adverts %}
    <div class="item">
        <div class="item_img">
            <a href="{% url 'catalog:advert_detail' advert.pk %}">
            {% thumbnail advert.cover__image "80x65" crop='center' as im %}
                <img src="{{ im.url }}">
            {% empty %}
                <img src="{% static "images/nophoto.jpg" %}">
            {% endthumbnail %}
            </a>
        </div>
        <div class="item_desc">
            <p class="desc"><a href="{% url 'catalog:advert_detail' advert.pk %}">{{ advert.title|truncatechars:35 }}</a></p>
            <p class="price">{{ advert.price }} ({{ advert.currency }})</p>
            <p>{{ advert.type|get_advert_type_display }}</p>
        </div>
        <div class="clr"></div>
    </div>
{% endfor %}
</div>