cabinet/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from .views import MessageListView, MessageCreateView, \
    MessageDialogListView, DeleteDialogView, DeleteMessageView, DeleteAccount

urlpatterns = patterns('cabinet.views',
    url(r'^$', 'view', name="view"),
    url(r'^edit/$', 'profile_edit', name='edit'),
    url(r'^drafts/$', 'drafts', name="drafts"),
    url(r'^draft/(?P<pk>\d+)/$', 'draft_edit', name='draft_edit'),
    url(r'^draft/(?P<pk>\d+)/delete/$', 'draft_delete', name='draft_delete'),
    url(r'^adverts/$', 'adverts', name="adverts"),
    url(r'^events/$', 'events', name='events'),
    url(r'^archive/$', 'events_archive', name='archive'),
    url(r'^comments/$', 'comments_list', name='comments'),
    url(r'^messages/$', MessageListView.as_view(), name='messages'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/$', MessageDialogListView.as_view(), name='dialog'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/delete/$', DeleteDialogView.as_view(), name='dialog_delete'),
    url(r'^messages/(?P<pk>\d+)/delete/$', DeleteMessageView.as_view(), name='message_delete'),
    url(r'^message/new/$', MessageCreateView.as_view(), name='message_new'),
    url(r'^delete/$', DeleteAccount.as_view(), name='delete_account'),

    # url(r'^draft/(?P<pk>\d+)/$', 'draft_view', name="draft_view"),
    # url(r'^(?P<pk>\d+)/$', 'get_profile', name='view'),
)

comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'add/$', 'comments.views.comment_add', name='comment_add'),
    url(r'delete/(?P<pk>\d+)/$', 'comments.views.comment_delete', name='comment_delete'),
)

event/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from event.views import EventListView, EventCreateView, EventDetailView, \
    EventEditView, EventUpView, CommitAddView, CommentPageView, \
    EventUploadView, EventUploadUrlView, EventUploadDeleteView, EventDeleteView
from core.views import event_make_like
from .models import Event

urlpatterns = patterns('',
    url(r'^$', EventListView.as_view(), name='list'),
    url(r'^events/add/$', EventCreateView.as_view(), name='create'),
    url(r'^events/(?P<pk>\d+)/$', EventDetailView.as_view(), name='detail'),
    url(r'^events/(?P<pk>\d+)/edit/$', EventEditView.as_view(), name='edit'),
    url(r'^events/(?P<pk>\d+)/edit/(?P<key>\w+)', EventEditView.as_view(),
        name='edit_for_key'),
    url(r'^events/(?P<pk>\d+)/up/$', EventUpView.as_view(), name='up'),
    url(r'^events/(?P<pk>\d+)/comment/add/$', CommitAddView.as_view(),
        name='comment_add'),
    url(r'^events/(?P<pk>\d+)/comment/$', CommentPageView.as_view(),
        name='comment_page'),

    url(r'^events/upload/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadView.as_view(), name='upload'),

    url(r'^events/upload_from_url/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadUrlView, name='upload_from_url'),

    url(r'^events/upload/del/(?P<pk>\d+)/(?P<field>\w+)/$',
        EventUploadDeleteView.as_view(), name='upload_del'),
    url(r'^events/delete/(?P<pk>\d+)/$',
        EventDeleteView.as_view(), name='delete'),

    url(r'^events/(?P<pk>\d+)/(?P<kind>["like"|"dislike"]+)/$', event_make_like, name='like'),
    # url(r'^events/(?P<pk>\d+)//$', event_make_dislike, name='dislike'),

    url(r'^events/img/(?P<pk>\d+)/$', 'catalog.views.img_add',
        {'model': Event}, name='img_add'),
    url(r'^events/img_url/(?P<pk>\d+)/$', 'catalog.views.img_url_add',
        {'model': Event}, name='img_url_add'),
    url(r'^events/img/(?P<pk>\d+)-(?P<image_pk>\d+)/(?P<action>delete|cover)/$',
        'catalog.views.img_control', {'model': Event}, name='img_control'),
)

infoportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.conf import settings
from event.views import EventListView
# from django_geoip.views import set_location

admin.autodiscover()

urlpatterns = patterns('',
    # home
    url(r'^$', EventListView.as_view(), name='home'),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^', include('registration.urls')),

    # for menu order
    # url(r'^pagesorter/orderedmove_order/(?P<direction>up|down)/(?P<model_type_id>\d+)/(?P<model_id>\d+)/$',
    #      'core.views.admin_move_ordered_model_order',
    #      name="admin_move_order"),

    # other apps
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
    url(r'^', include('event.urls', 'event')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # url(r'^article/', include('core.urls', namespace='core')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # geo
    url(r'^geo/regions/$', 'core.views.get_regions', name='get_regions'),
    url(r'^geo/region-(?P<region_pk>\d+)/$', 'core.views.get_cities', name='get_cities'),
    url(r'^geo/city/autocomplete/$', 'core.views.city_autocomplete', name='city_autocomplete'),
    # url(r'^geoip/', include('django_geoip.urls')),
    # url(r'^geoip/setlocation/', 'core.views.set_location', name='geoip_change_location'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('search.urls')),
    url(r'^', include('catalog.urls', app_name="catalog", namespace='catalog')),
    url(r'^', include('event.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

event/models.py
# -*- encoding: utf-8 -*-
import math
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.template.defaultfilters import filesizeformat
from django.utils import timezone
from dateutils import relativedelta
from core.helpers import site_settings
from django.core.urlresolvers import reverse
from sorl.thumbnail import get_thumbnail

from event.fields import ContentTypeRestrictedFileField
from event.mixins import FileKirilicMixin
from core.models import LocCity, LocRegion
from core.utils import mat_validator


class EventCategory(models.Model):
    title = models.CharField(_(u'название'), max_length=255)
    icon_name = models.CharField(
        _(u'иконка'), max_length=255, null=True, blank=True,
        help_text=_(u'название иконок брать тут http://fortawesome.github.io/'
                    u'Font-Awesome/icons/'))
    hidden = models.BooleanField(u'скрыть', default=False,
                                 help_text=u'Будет скрыто, если отмечено')

    class Meta:
        verbose_name = _(u'Группа ивентов')
        verbose_name_plural = _(u'Группы ивентов')

    def __unicode__(self):
        return unicode(self.title)


class EventManager(models.Manager):

    def get_queryset(self):
        return super(EventManager, self).get_queryset()\
            .filter(title__isnull=False)

    def get_archive(self):
        """
            Ивенты в которых истех срок годности + значение с настроек
        """
        x_date = timezone.now() - relativedelta(days=site_settings.EVENT_REG_ON_FEED)
        return self.filter(datetime__lt=x_date)

    def get_actual(self):
        """
            Ивенты которые еще не попали в архив
        """
        x_date = timezone.now() - relativedelta(days=site_settings.EVENT_REG_ON_FEED)
        return self.exclude(datetime__lt=x_date)
        # return self.all()


class Event(FileKirilicMixin, models.Model):
    # file_filed = ['photo', 'audio','photo_from_url_1','photo_from_url_2','photo_from_url_3','photo_from_url_4']

    user = models.ForeignKey(
        'cabinet.UserProfile', verbose_name=_(u'пользователь'),
        null=True, blank=True, related_name='events')
    session_key = models.CharField(
        _(u'Ключ сессии автора'), max_length=80, null=True, blank=True)
    edit_key = models.CharField(
        _(u'Ключ редактирования'), max_length=80, null=True, blank=True)
    title = models.CharField(_(u'заголовок'), max_length=200, null=True)
    category = models.ForeignKey(
        'EventCategory', verbose_name=_(u'категория'), null=True)
    description = models.TextField(_(u'описание'))
    name = models.CharField(_(u'имя'), max_length=60, null=True, blank=True)
    email = models.EmailField(_(u'email'), null=True, blank=True)
    skype = models.CharField(_(u'skype'), max_length=40, null=True, blank=True)
    phone = models.CharField(_(u'телефон'), max_length=20,
                             null=True, blank=True)
    address = models.CharField(_(u'адрес'), max_length=255,
                               null=True, blank=True)
    keywords = models.CharField(
        u'ключевые слова', max_length=254, blank=True, null=True,
        help_text=u'Через запятую.')
    datetime = models.DateTimeField(_(u'начало'), null=True)
    cover = models.ForeignKey(
        'EventImage', verbose_name=u'обложка', related_name='event_covered',
        on_delete=models.SET_NULL, null=True, blank=True)
    audio = ContentTypeRestrictedFileField(
        _(u'аудио файл'), upload_to='events/audio/', null=True, blank=True,
        content_types=('audio/mpeg3', 'audio/x-mpeg-3', 'audio/mp3',
                       'audio/mpeg'), max_length=200)
    created = models.DateTimeField(_(u'создано'), default=timezone.now)
    ordering = models.DateTimeField(_(u'дата сортировки'), default=timezone.now)
    upper_count = models.PositiveIntegerField(
        _(u'количество поднятий'), default=0)

    # координаты
    region = models.ForeignKey(
        LocRegion, verbose_name=u'регион', null=True, blank=True)
    city = models.ForeignKey(
        LocCity, verbose_name=u'город', null=True, blank=True)

    comments_count = models.PositiveIntegerField(
        u'кол-во комментариев', default=0)
    likes_count = models.PositiveIntegerField(
        u'кол-во позитивных лайков', default=0)
    dislike_count = models.PositiveIntegerField(
        u'кол-во негативных лайков', default=0)
    objects_all = models.Manager()
    objects = EventManager()
    base_manager = models.Manager()

    class Meta:
        verbose_name = _(u'Ивент')
        verbose_name_plural = _(u'Ивенты')
        ordering = ('-ordering',)

    def __unicode__(self):
        return unicode(self.title)

    def get_cover_image(self):
        if self.cover and self.cover.image:
            return self.cover.image
        else:
            first = self.eventimage_set.first()
            return first.image if first else None

    def get_comments(self):
        return self.comments.filter(parent__isnull=True)

    def get_event_page_count(self):
        return math.ceil(
            self.comments.filter(parent__isnull=True).count() / 10.)

    def get_comments_first_page(self):
        return self.comments.filter(parent__isnull=True)[:10]

    def get_comments_by_page(self, page):
        return self.comments.filter(
            parent__isnull=True)[(page - 1) * 10:page * 10]

    def get_audio_name(self):
        if self.audio:
            return self.audio.name.split('/')[-1]
        return ''

    def get_audio_size(self):
        if self.audio:
            return filesizeformat(self.audio.size)
        return ''

    @property
    def is_actual(self):
        return True if self.datetime > timezone.now() else False

    def update_comments_count(self):
        self.comments_count = self.comments.count()
        self.save()

    def update_likes_count(self):
        self.likes_count = self.likes.filter(type=1).count()
        self.dislike_count = self.likes.filter(type=2).count()
        self.save()


class EventImage(models.Model):
    image = models.ImageField(u'Изображение', upload_to='events/photo/')
    advert = models.ForeignKey(Event, verbose_name=u'Ивент')

    class Meta:
        verbose_name = u'Изображение'
        verbose_name_plural = u'Изображения'

    def __unicode__(self):
        return u'Изображение'

    def get_delete_url(self):
        return reverse(
            'event:img_control', args=(self.advert_id, self.id, 'delete'))

    def get_cover_url(self):
        return reverse(
            'event:img_control', args=(self.advert_id, self.id, 'cover'))

    def get_thumbnail(self, size='75x75', crop='center', quality=99):
        img = self.image
        return unicode(get_thumbnail(img, size, crop=crop, quality=quality).url)

    def get_thumbnail_html(self):
        html = '<img src="{0}" alt="img"/>'
        return html.format(self.get_thumbnail())


class Comment(models.Model):
    event = models.ForeignKey(
        'Event', verbose_name=_(u'ивент'), related_name='comments')
    parent = models.ForeignKey(
        'self', related_name='children', verbose_name=_(u'предок'),
        null=True, blank=True)
    user = models.ForeignKey(
        'cabinet.UserProfile', verbose_name=_(u'Пользователь'),
        related_name='event_comments')
    message = models.TextField(_(u'Коментарий'), validators=[mat_validator])
    created = models.DateTimeField(_(u'Создано'), default=timezone.now)

    class Meta:
        verbose_name = _(u'Коментарий')
        verbose_name_plural = _(u'Коментарии')
        ordering = ('-created',)

    def __unicode__(self):
        return unicode(self.user)

    def get_children(self):
        return self.children.all().order_by('created')


TYPE_LIKE = (
    (0, None),
    (1, 'like'),
    (2, 'dislike')
)


class Like(models.Model):
    event = models.ForeignKey(
        'Event', verbose_name=_(u'ивент'), related_name='likes')
    user = models.ForeignKey(
        'cabinet.UserProfile', verbose_name=_(u'Пользователь'),
        related_name='event_likes')
    type = models.SmallIntegerField(_('Тип'), choices=TYPE_LIKE)

    class Meta:
        verbose_name = _(u'лайк')
        verbose_name_plural = _(u'лайки')

    def __unicode__(self):
        return u'like'

comments/views.py
# -*- coding: utf-8 -*-
import json
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
# from django.utils import simplejson
from django.views.decorators.http import require_POST
from django.core.urlresolvers import resolve
from django.utils.six.moves.urllib.parse import urlparse
from django.utils.http import is_safe_url

from comments.forms import CommentForm
from comments.models import Comment
from core.utils import ajax_required

from sorl.thumbnail import get_thumbnail


@login_required
def comment_add(request):

    def comment_save(form, addr):
        comment = form.save(commit=False)
        comment.user_id = form.user_id
        comment.content_object = form.target_object
        comment.ip = addr
        comment.save()
        return comment

    def get_next(request, url):
        if not is_safe_url(url=url, host=request.get_host()):
            url = '/'
        return HttpResponseRedirect(url)

    next_param = 'next'
    next_page = None
    if (next_param in request.POST or next_param in request.GET):
        next_page = request.POST.get(next_param, request.GET.get(next_param))

    form = CommentForm(request.user, request.POST)

    if request.method == 'POST' and request.is_ajax():
        if form.is_valid():
            comment = comment_save(form, request.META['REMOTE_ADDR'])
            data = json.dumps({'success': True,
                               'user': comment.get_name(),
                               'date': comment.get_date(),
                               'text': comment.text,
                               'image': get_thumbnail(request.user.avatar,
                                                      '50x50',
                                                      crop='center',
                                                      quality=99).url})
        else:
            data = json.dumps({'form_errors': form.errors})
        return HttpResponse(data, mimetype='application/json')
    elif request.method == 'POST':
        if form.is_valid():
            comment_save(form, request.META['REMOTE_ADDR'])
            return get_next(request, next_page)
        else:
            view, args, kwargs = resolve(urlparse(next_page)[2])
            request.method = 'GET'
            kwargs.update({'request': request,
                           'comment_form': form})
            return view(*args, **kwargs)
    else:
        return get_next(request, next_page)


@login_required
def comment_delete(request, pk):
    """
        delete advert view
    """
    obj = get_object_or_404(Comment, pk=pk)
    if obj.user == request.user:
        obj.delete()
        messages.success(request, _(u'Комментарий успешно удалено'))
    else:
        messages.error(request, _(u'У вас нет прав на это действие'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

event/templates/event/comment_child.html
{% load static %}
<div class="children_user_comment">
  <div class="user_image">
    {% if children.user.avatar %}
      <img src="{{ children.user.avatar.url }}">
    {% else %}
      <img src="{% static 'images/avatar.gif' %}">
    {% endif %}
  </div>
  <div class="comment_info">
    <p class="us_info">
      {% if children.user.is_vk %}
        <a href="http://vk.com/id{{ children.user.get_vk_uid }}" target="_blank">
          <i class="fa fa-vk"></i>
        </a>
      {% else %}
        <span class="topby">topclub</span>
      {% endif %}, {{ children.user.username }}, {{ children.created }}
    </p>

    <p class="comment_body">{{ children.message }}</p>
  </div>
  {% if request.user.is_authenticated %}
    <a href="#" class="private_message">Личное сообщение</a>
    <a href="{% url 'cabinet:message_new' %}?to={{ children.user.username }}" class="re-message quote" data-id="{{ comment.id }}">Ответить</a>
  {% endif %}
  <div class="clear"></div>
</div>

event/templates/event/comments.html
{% load static i18n %}
<div class="user_comments">
  {% for comment in comments %}
    <div class="user_comment clearfix" id="comment-{{ comment.id }}">
      <div class="user_image">
        {% if comment.user.avatar %}
          <img src="{{ comment.user.avatar.url }}">
        {% else %}
          <img src="{% static 'images/avatar.gif' %}">
        {% endif %}
      </div>
      <div class="comment_info">
        <p class="us_info">
          {% if comment.user.is_vk %}
            <a href="http://vk.com/id{{ comment.user.get_vk_uid }}" target="_blank">
              <i class="fa fa-vk"></i>
            </a>
          {% else %}
            <span class="topby">topclub</span>
          {% endif %}, {{ comment.user.username }}, {{ comment.created }}
        </p>

        <p class="comment_body">{{ comment.message }}</p>
      </div>
      <a href="#" class="re-message quote" data-id="{{ comment.id }}">Ответить</a>
      <a href="{% url 'cabinet:message_new' %}?to={{ comment.user.username }}" class="private_message">Личное сообщение</a>
      <div class="clear"></div>
      {% for children in comment.get_children %}
        <div class="children_user_comment">
          <div class="user_image">
            {% if children.user.avatar %}
              <img src="{{ children.user.avatar.url }}">
            {% else %}
              <img src="{% static 'images/avatar.gif' %}">
            {% endif %}
          </div>
          <div class="comment_info">
            <p class="us_info">
              {% if children.user.is_vk %}
                <a href="http://vk.com/id{{ children.user.get_vk_uid }}" target="_blank"><i class="fa fa-vk"></i></a>
              {% else %}
                <span class="topby">topclub</span>
              {% endif %}, {{ children.user.username }}, {{ children.created }}
            </p>
            <p class="comment_body">{{ children.message }}</p>
          </div>
          {% if request.user.is_authenticated %}
            <a href="#" class="re-message quote" data-id="{{ comment.id }}">Ответить</a>
            <a href="{% url 'cabinet:message_new' %}?to={{ children.user.username }}" class="private_message">Личное сообщение</a>
          {% endif %}
          <div class="clear"></div>
        </div>
      {% endfor %}
    </div>
  {% endfor %}
</div>

{% if event.get_event_page_count <= page %}
  <script type="text/javascript">
    $(document).ready(function() {
      $('#get-messages').hide();
    })
  </script>
{% endif %}

event/templates/event/create.html
{% extends "base_events.html" %}
{% load i18n staticfiles thumbnail cache registration_tags core_tags widget_tweaks chat_tags %}

{% chat_head %}

{% block title %}{% trans 'Добавить ивент' %}{% endblock %}

{% block javascript %}
    <script type="text/javascript" src="http://api-maps.yandex.ru/2.0-stable/?load=package.standard&lang=ru-RU"></script>
    <script type='text/javascript' src="{% static 'js/jquery.maskedinput.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.form.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/image.js' %}"></script>
    <script type="text/javascript">
        ymaps.ready(function(){
            var myMap, myPlacemark;
            var lat = 53.9;
            var lng = 27.56667;

            myMap = new ymaps.Map('map', {
                center: [lat, lng],
                zoom: 12,
                behaviors: ["default", "scrollZoom"]
            });
            if ($('#id_address').val()) {
                var address = $('#id_address').val().split(';;');
                var lt = address[0];
                var lg = address[1];
                $('#id_lat').val(lt);
                $('#id_lng').val(lg);
                myPlacemark = new ymaps.Placemark([lt, lg], {
                    hintContent: $('#id_title').val(),
                    balloonContent: $('#id_description').val()
                });
                myMap.geoObjects.add(myPlacemark);
            }
            myMap.events.add('click', function (e) {
                if(myPlacemark)
                    myMap.geoObjects.remove(myPlacemark);

                var position = e.get('coordPosition');

                var lat = position[0];
                var lng = position[1];
                $('#id_lat').val(lat);
                $('#id_lng').val(lng);
                $('#id_address').val(lat + ';;' + lng);

                myPlacemark = new ymaps.Placemark([lat, lng], {
                    hintContent: $('#id_title').val(),
                    balloonContent: $('#id_description').val()
                });
                myMap.geoObjects.add(myPlacemark);
            });

        });
        jQuery(function($){
            $("#id_phone").mask("+375 (99) 9999999");
            $('.loader').hide();
            img_upload({
                max_img: 4,
                max_img_text: '{% trans 'Максимальное количество изображений для ивента - 4 шт.' %}',
                main_img_text: '{% trans 'Сделать обложкой' %}',
                url: '{% url 'event:img_url_add' pk=obj.pk %}'

            });
            $(document.body).on('click', '.audio_del', function(){
                $.ajax({
                    type: "GET",
                    url: $(this).attr('href'),
                    complete: function(res) {
                        $('.audio_previews').html('');
                        $('#id_audio').val('');
                    }
                });
                return false;
            });

            $('#add_form').submit(function(){
                $('#id_photo').val('');
                $('#id_audio').val('');
            });
            $('#id_audio').change(function(){
                $('.error-audio').html('');
                $('#submit_button').attr('disabled', '');
                $('#audio_loader').show();
                var form = $('#add_form');
                $(form).ajaxSubmit({
                    url: "{% url 'event:upload' pk=obj.pk field='audio' %}",
                    type: form.method,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            $('.audio_previews').html('<a href="' + data.url +'" class="audio_link">' + data.name + '</a> ' + data.size + ' <a class="audio_del" href="{% url 'event:upload_del' pk=obj.pk field='audio' %}"><i class="fa fa-trash-o"></i></a>')
                        } else {
                            $('.error-audio').html(data.error);
                        }
                    },
                    complete: function(data){
                        $('#id_audio').val('');
                        $('#audio_loader').hide();
                        $('#submit_button').removeAttr('disabled');
                    }
                });
            });
        });
    </script>
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'event:list' %}">{% trans 'Все Ивенты' %}</a>
{% endblock breadcrumbs %}

{% block content %}
    <div class="wrap-form">
        {#        <div class="content center url-form-wrap">#}
        {#            <form action="" method="post" enctype="multipart/form-data" id='form_url'>#}
        {#                {% csrf_token %}#}
        {#          <input id="id_geo_init" type="hidden" value="{{ request.location.get_lnglat }}" name="geo_init">#}
        {#                <div id='photo_from_url'>#}
        {#                    {% trans 'Вставьте ссылку и нажмите Enter' %}#}
        {#                    <br><br>#}
        {#                    <label for="id_img_from_url">{% trans 'Фото по url' %}</label>#}
        {#                    <input id="id_img_from_url" maxlength="500" name="img_from_url" type="text" form="form_url" />#}
        {#                </div>#}
        {#            </form>#}
        {#        </div>#}
        <form action="" method="post" class="add_event_form" id="add_form" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form.hidden_fields %}
                {{ field }}
                {{ field.errors }}
            {% endfor %}

            {% for field in form.visible_fields %}
                <div class="form-group {% if field.errors %}has-error{% endif %}">
                    {% if not field.name in 'address' %}<label class="control-label">{{ field.label }}</label>{% endif %}
                    {% render_field field class='form-control' %}
                    <span class="error error-{{ field.name }}">{% for error in field.errors %}{{ error }}{% if not forloop.last %}<br>{% endif %}{% endfor %}</span>

                    {% if forloop.last %}
                        <div class="form_group map_control">
                            <label class="control-label">{% trans 'Отметьте местопроведение иветна' %}</label>
                            <div id="map"></div>
                        </div>
                    {% endif %}
                </div>
                {% if field.name in 'description' %}
                    <fieldset class="wrap-previw-button">
                        <label class="control-label" >Изображение</label>
                        <br/>
                        {% for field in img_form.visible_fields %}
                            {{ field }}
                            {{ field.errors }}
                        {% endfor %}
                    </fieldset>
                    <div id='photo_from_url'>
                        <label for="id_img_from_url" class="control-label" >{% trans 'Фото по url' %}</label>
                        <input id="id_img_from_url" maxlength="500" name="img_from_url" type="text" form="form_url" />
                    </div>
                    {#   картинки         #}
                    <div class="img_errors"></div>
                    <div class="img_previews">
                        {{ images }}
                        {% for image in images %}
                            <div class="preview {% ifequal cover_pk image.id %}active{% endifequal %}">

                                {% thumbnail image.image "75x75" crop='center' as im %}
                                    <img src="{{ im.url }}">
                                {% endthumbnail %}
                                <a class="preview_del" href="{{ image.get_delete_url }}"></a>
                                <a class="cover_url" href="{{ image.get_cover_url }}">Сделать обложкой</a>
                            </div>
                        {% endfor %}
                    </div>
                    {# картинки #}
                    <div class="form-group">
                        <label class="control-label">{% trans 'Аудио' %}</label>
                        <input class="form-control" id="id_audio" name="audio" type="file" />
                        <span class="error error-audio"></span>
                        <div class="loader" id="audio_loader"><img src="{% static 'images/ajax-loader2.gif' %}"></div>
                        <div class="audio_previews">
                            {%  if obj.audio %}
                                <a href="{{ obj.audio.url }}" class="audio_link">{{ obj.get_audio_name }}</a> {{ obj.get_audio_size }}
                                <a class="audio_del" href="{% url 'event:upload_del' pk=obj.pk field='audio' %}"><i class="fa fa-trash-o"></i></a>
                            {% endif %}
                        </div>
                    </div>
                {% endif %}
            {% endfor %}
            <div class="form-group">
                <button type="submit" class="btn btn-primary" id="submit_button">{% trans 'Создать' %}</button>
            </div>
        </form>
    </div>
{% endblock %}