comments/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'add/$', 'comments.views.comment_add', name='comment_add'),
    url(r'delete/(?P<pk>\d+)/$', 'comments.views.comment_delete', name='comment_delete'),
)

infoportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.conf import settings
from event.views import EventListView
# from django_geoip.views import set_location

admin.autodiscover()

urlpatterns = patterns('',
    # home
    url(r'^$', EventListView.as_view(), name='home'),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^', include('registration.urls')),

    # for menu order
    # url(r'^pagesorter/orderedmove_order/(?P<direction>up|down)/(?P<model_type_id>\d+)/(?P<model_id>\d+)/$',
    #      'core.views.admin_move_ordered_model_order',
    #      name="admin_move_order"),

    # other apps
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
    url(r'^', include('event.urls', 'event')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # url(r'^article/', include('core.urls', namespace='core')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # geo
    url(r'^geo/regions/$', 'core.views.get_regions', name='get_regions'),
    url(r'^geo/region-(?P<region_pk>\d+)/$', 'core.views.get_cities', name='get_cities'),
    url(r'^geo/city/autocomplete/$', 'core.views.city_autocomplete', name='city_autocomplete'),
    # url(r'^geoip/', include('django_geoip.urls')),
    # url(r'^geoip/setlocation/', 'core.views.set_location', name='geoip_change_location'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('search.urls')),
    url(r'^', include('catalog.urls', app_name="catalog", namespace='catalog')),
    url(r'^', include('event.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comments/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

from cabinet.models import UserProfile as User
from core.utils import UCrypto, mat_validator


class Comment(models.Model):

    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        get_latest_by = 'created'

    ip = models.GenericIPAddressField(u'IP address', unpack_ipv4=True, blank=True, null=True)
    created = models.DateTimeField(u'дата создания', auto_now_add=True)
    hidden = models.BooleanField(u'скрыть', default=False, help_text=u'Будет скрыто, если отмечено')

    user = models.ForeignKey(User, verbose_name=u'Пользователь')
    text = models.TextField(u'сообщение', validators=[mat_validator])

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def get_name(self):
        return self.user.get_full_name()

    def get_date(self):
        return self.created.strftime('%d %B %Y %H:%M')

    def __unicode__(self):
        return self.get_date()

comments/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib.contenttypes.models import ContentType

from comments.models import Comment
from core.utils import UCrypto


class CommentForm(forms.ModelForm):
    key = forms.CharField(widget=forms.HiddenInput)

    class Meta:
        model = Comment
        # widgets = {'key': forms.HiddenInput}
        exclude = ('ip', 'created', 'hidden', 'user', 'content_type', 'object_id')

    _error_messages = {
        'invalid_key': _(u'Неверный ключ записи. Попробуйте еще раз.')
        }

    def __init__(self, user, data=None, target_object=None, initial=None):
        super(CommentForm, self).__init__(data=data, initial=initial)
        self.user_id = user.pk
        if target_object:
            key = UCrypto(
                ContentType.objects.get_for_model(target_object).pk,
                target_object.pk,
                self.user_id,
            ).encode()
            self.fields['key'].initial = key

    def clean_key(self):
        key = UCrypto(self.cleaned_data.get('key')).decode().split(',')
        try:
            if not all([len(key) == 3, self.user_id == int(key[2])]):
                raise KeyError
            ctype = ContentType.objects.get_for_id(int(key[0]))
            target_object = ctype.get_object_for_this_type(id=int(key[1]))
        except (ContentType.DoesNotExist, KeyError):
            raise forms.ValidationError(self._error_messages['invalid_key'])
        self.target_object = target_object
        return key

comments/views.py
# -*- coding: utf-8 -*-
import json
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
# from django.utils import simplejson
from django.views.decorators.http import require_POST
from django.core.urlresolvers import resolve
from django.utils.six.moves.urllib.parse import urlparse
from django.utils.http import is_safe_url

from comments.forms import CommentForm
from comments.models import Comment
from core.utils import ajax_required

from sorl.thumbnail import get_thumbnail


@login_required
def comment_add(request):

    def comment_save(form, addr):
        comment = form.save(commit=False)
        comment.user_id = form.user_id
        comment.content_object = form.target_object
        comment.ip = addr
        comment.save()
        return comment

    def get_next(request, url):
        if not is_safe_url(url=url, host=request.get_host()):
            url = '/'
        return HttpResponseRedirect(url)

    next_param = 'next'
    next_page = None
    if (next_param in request.POST or next_param in request.GET):
        next_page = request.POST.get(next_param, request.GET.get(next_param))

    form = CommentForm(request.user, request.POST)

    if request.method == 'POST' and request.is_ajax():
        if form.is_valid():
            comment = comment_save(form, request.META['REMOTE_ADDR'])
            data = json.dumps({'success': True,
                               'user': comment.get_name(),
                               'date': comment.get_date(),
                               'text': comment.text,
                               'image': get_thumbnail(request.user.avatar,
                                                      '50x50',
                                                      crop='center',
                                                      quality=99).url})
        else:
            data = json.dumps({'form_errors': form.errors})
        return HttpResponse(data, mimetype='application/json')
    elif request.method == 'POST':
        if form.is_valid():
            comment_save(form, request.META['REMOTE_ADDR'])
            return get_next(request, next_page)
        else:
            view, args, kwargs = resolve(urlparse(next_page)[2])
            request.method = 'GET'
            kwargs.update({'request': request,
                           'comment_form': form})
            return view(*args, **kwargs)
    else:
        return get_next(request, next_page)


@login_required
def comment_delete(request, pk):
    """
        delete advert view
    """
    obj = get_object_or_404(Comment, pk=pk)
    if obj.user == request.user:
        obj.delete()
        messages.success(request, _(u'Комментарий успешно удалено'))
    else:
        messages.error(request, _(u'У вас нет прав на это действие'))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER', '/'))

comments/templates/comment_form.html
<form method="post" id="comment-form" action="{% url 'comments:comment_add' %}{% if next %}?next={{ next }}{% endif %}">
    <header>Оставьте свой комментарий</header>
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name="save" class="comment_add_button" value="Отправить">
</form>

comments/templates/comments_list.html
{% load comments_tags staticfiles thumbnail %}

{% get_paginator comments %}
<div class="user_comments">
{% for comment in comments %}
    <div class="user_comment">
        <div class="user_image">
        {% thumbnail comment.user.avatar "50x50" crop='center' as im %}
            <img src="{{ im.url }}" >
        {% empty %}
            <img src="{% static "images/avatar.gif" %}" class="avatar">
        {% endthumbnail %}
        </div>
        <div class="comment_info">
            <p class="us_info">{{ comment.get_name }}, {{ comment.get_date }}</p>
            <p class="comment_body">{{ comment.text }}</p>
        </div>
        <a href="#" class="quote">Цитировать</a>
        <div class="clear"></div>
    </div>
{% endfor %}
</div>
{% get_paginator comments %}

comments/templates/comments_pagination.html
<div class="pagination">
    {% if page_obj.has_previous %}
        <a class="prev" href="?{{ page_key }}={{ page_obj.previous_page_number }}"></a>
    {% else %}
        <a class="prev"></a>
    {% endif %}

    {% if show_first %}
        <a href="?{{ page_key }}=1">1</a>
        <a>...</a>
    {% endif %}

    {% for page in page_numbers %}
            {% ifequal page page_obj.number %}
                <a class="active">{{ page }}</a>
            {% else %}
                <a href="?{{ page_key }}={{ page }}">{{ page }}</a>
            {% endifequal %}
    {% endfor %}

    {% if show_last %}
       <a>...</a>
        <a href="?{{ page_key }}={{ page_obj.paginator.num_pages }}">
            {{ page_obj.paginator.num_pages }}
        </a>
    {% endif %}

    {% if page_obj.has_next %}
        <a class="next" href="?{{ page_key }}={{ page_obj.next_page_number }}"></a>
    {% else %}
        <a class="next"></a>
    {% endif %}
</div>