cabinet/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from .views import MessageListView, MessageCreateView, \
    MessageDialogListView, DeleteDialogView, DeleteMessageView, DeleteAccount

urlpatterns = patterns('cabinet.views',
    url(r'^$', 'view', name="view"),
    url(r'^edit/$', 'profile_edit', name='edit'),
    url(r'^drafts/$', 'drafts', name="drafts"),
    url(r'^draft/(?P<pk>\d+)/$', 'draft_edit', name='draft_edit'),
    url(r'^draft/(?P<pk>\d+)/delete/$', 'draft_delete', name='draft_delete'),
    url(r'^adverts/$', 'adverts', name="adverts"),
    url(r'^events/$', 'events', name='events'),
    url(r'^archive/$', 'events_archive', name='archive'),
    url(r'^comments/$', 'comments_list', name='comments'),
    url(r'^messages/$', MessageListView.as_view(), name='messages'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/$', MessageDialogListView.as_view(), name='dialog'),
    url(r'^messages/dialog/(?P<username>[\w-]+)/delete/$', DeleteDialogView.as_view(), name='dialog_delete'),
    url(r'^messages/(?P<pk>\d+)/delete/$', DeleteMessageView.as_view(), name='message_delete'),
    url(r'^message/new/$', MessageCreateView.as_view(), name='message_new'),
    url(r'^delete/$', DeleteAccount.as_view(), name='delete_account'),

    # url(r'^draft/(?P<pk>\d+)/$', 'draft_view', name="draft_view"),
    # url(r'^(?P<pk>\d+)/$', 'get_profile', name='view'),
)

catalog/urls.py
from django.conf.urls import patterns, url
from .models import Advert

urlpatterns = patterns('catalog.views',
    url(r'^market/$', 'flea_market', name='market'),
    url(r'^view/(?P<pk>\d+)/$', 'advert_detail', name='advert_detail'),
    url(r'^edit/(?P<pk>\d+)/$', 'advert_edit', name='advert_edit'),
    url(r'^delete/(?P<pk>\d+)/$', 'advert_delete', name='advert_delete'),
    url(r'^notactual/(?P<pk>\d+)/$', 'advert_notactual', name='advert_notactual'),
    url(r'^add/new/$', 'advert_new', name='new'),
    
    url(r'^add/(?P<pk>\d+)/$', 'advert_add', name='add'),

    url(r'^img/(?P<pk>\d+)/$', 'img_add', {'model': Advert}, name='img_add'),
    url(r'^img_url/(?P<pk>\d+)/$', 'img_url_add', {'model': Advert}, name='img_url_add'),
    url(r'^img/(?P<pk>\d+)-(?P<image_pk>\d+)/(?P<action>delete|cover)/$',
        'img_control', {'model': Advert}, name='img_control'),

    url(r'^(?P<slug>[\w-]+)/$', 'catalog_detail', name='detail'),
    url(r'^category/(?P<slug>[\w-]+)/$', 'category_detail', name='category_detail'),

)

infoportal/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from django.contrib import admin
from django.conf import settings
from event.views import EventListView
# from django_geoip.views import set_location

admin.autodiscover()

urlpatterns = patterns('',
    # home
    url(r'^$', EventListView.as_view(), name='home'),

    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # registration
    url(r'^', include('registration.urls')),

    # for menu order
    # url(r'^pagesorter/orderedmove_order/(?P<direction>up|down)/(?P<model_type_id>\d+)/(?P<model_id>\d+)/$',
    #      'core.views.admin_move_ordered_model_order',
    #      name="admin_move_order"),

    # other apps
    url(r'^comment/', include('comments.urls', namespace='comments')),
    url(r'^cabinet/', include('cabinet.urls', namespace='cabinet')),
    url(r'^', include('event.urls', 'event')),
    url(r'^ckeditor/', include('ckeditor.urls')),
    # url(r'^article/', include('core.urls', namespace='core')),
    url(r'^captcha/', include('captcha.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

    # geo
    url(r'^geo/regions/$', 'core.views.get_regions', name='get_regions'),
    url(r'^geo/region-(?P<region_pk>\d+)/$', 'core.views.get_cities', name='get_cities'),
    url(r'^geo/city/autocomplete/$', 'core.views.city_autocomplete', name='city_autocomplete'),
    # url(r'^geoip/', include('django_geoip.urls')),
    # url(r'^geoip/setlocation/', 'core.views.set_location', name='geoip_change_location'),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('search.urls')),
    url(r'^', include('catalog.urls', app_name="catalog", namespace='catalog')),
    url(r'^', include('event.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import patterns, url
from search.views import search

urlpatterns = patterns('',
    url(r'^search/$', search, name='search'),
)

cabinet/models.py
# -*- coding:utf-8 -*-
import urllib2
from urlparse import urlparse
from sorl.thumbnail import get_thumbnail

from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.core import validators
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.utils.translation import ugettext_lazy as _
from django.utils.html import format_html
from django.utils import timezone
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile

from core.utils import path
from core.models import LocCity, LocRegion
# from random import choice
# import string


# def _rand_key(size=20):
#     return ''.join([choice(string.letters + string.digits) for i in range(size)])


def avatar_path(*args):
    """
    Returns a file path where to save a photo/image
    Default args are: instance, filename
    Also u can provide kwarg 'path' to path. Only string.
    """
    return path(*args, path='avatar')


class UserProfile(AbstractBaseUser, PermissionsMixin):
    is_staff = models.BooleanField(_('staff status'), default=False,
        help_text=_('Designates whether the user can log into this admin '
                    'site.'))
    is_active = models.BooleanField(_('active'), default=True,
        help_text=_('Designates whether this user should be treated as '
                    'active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    # наши данные
    username = models.CharField(_('username'), max_length=30, unique=True,
        help_text=_(u'Обязательное поле. Не более 30 символов. Только буквы, '
                    u'цифры и символы -._'),
        validators=[
            validators.RegexValidator(r'^[\w.-]{3,30}$', _('Enter a valid username.'), 'invalid')
        ])
    email = models.EmailField(u'E-mail', unique=True)
    first_name = models.CharField(u'имя', max_length=20)
    last_name = models.CharField(u'фамилия', max_length=20)
    phone = models.CharField(u"Телефон", max_length=255, default='', blank=True, null=True)
    avatar = models.ImageField(u'аватар', upload_to=avatar_path,
                                max_length=250, blank=True, null=True)
    by_line = models.TextField(u"Подпись", default='', blank=True, null=True)

    admin_region = models.ForeignKey(
        LocRegion, verbose_name=u'регион', null=True, blank=True, related_name='admin_region')
    # geoip
    city = models.ForeignKey(LocCity, verbose_name=u'город', null=True)
    region = models.ForeignKey(LocRegion, verbose_name=u'регион', null=True)

    objects = UserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    class Meta:
        verbose_name = u'пользователь'
        verbose_name_plural = u'пользователи'

    def __unicode__(self):
        return '%s (%s)' % (self.email, self.get_full_name())

    def admin_list_display(self):
        return format_html(u'{0}<br>{1}'.format(self.email, self.get_full_name()))

    def get_short_name(self):
        return self.username if not self.social_auth.exists() \
            else self.get_full_name()

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def email_user(self, subject, message, from_email=None):
        send_mail(subject, message, from_email, [self.email])

    def get_absolute_url(self):
        return reverse('cabinet:view', args=(self.pk,))

    def get_chat_avatar(self):
        if self.avatar:
            return get_thumbnail(self.avatar, '25x25', crop='center', quality=99).url
        return '/static/images/avatar25x25.gif'

    @staticmethod
    def autocomplete_search_fields():
        return ("id__iexact", "username__icontains", "email__icontains",)

    def is_vk(self):
        return self.social_auth.exists()

    def get_vk_uid(self):
        if not self.is_vk():
            return None
        return self.social_auth.all()[0].uid

    def count_new_message(self):
        return self.received_messages.filter(read_at__isnull=True).count()


def set_vk_avatar(sender, instance, created, **kwargs):
    if not instance.avatar and instance.social_auth.exists():
        try:
            url = instance.social_auth.all()[0].extra_data['photo_200']
            name = urlparse(url).path.split('/')[-1]
            img_temp = NamedTemporaryFile(delete=True)
            img_temp.write(urllib2.urlopen(url).read())
            img_temp.flush()
            instance.avatar.save(name, File(img_temp))
        except AttributeError:
            pass

models.signals.post_save.connect(set_vk_avatar, sender=UserProfile)


class MessageManager(models.Manager):

    def get_messages(self, user):
         return self.filter(
             models.Q(sender=user, sender_deleted_at__isnull=True) |
             models.Q(recipient=user, recipient_deleted_at__isnull=True)
         )

    def get_dialog(self, user, user2):
        return self.filter(
            (models.Q(sender=user, sender_deleted_at__isnull=True) & models.Q(recipient=user2)) |
            (models.Q(sender=user2) & models.Q(recipient=user, recipient_deleted_at__isnull=True))
        )

    def trash_for(self, user):
        """
        Returns all messages that were either received or sent by the given
        user and are marked as deleted.
        """
        return self.filter(
            recipient=user,
            recipient_deleted_at__isnull=False,
        ) | self.filter(
            sender=user,
            sender_deleted_at__isnull=False,
        )

    def count_unread(self, user):
        return self.filter(recipient=user, read_at__isnull=True).count()


class Message(models.Model):
    """
    A private message from user to user
    """
    subject = models.CharField(_(u"Тема"), max_length=120)
    body = models.TextField(_(u"Текст"))
    sender = models.ForeignKey('UserProfile', related_name='sent_messages', verbose_name=_(u"Отправитель"))
    recipient = models.ForeignKey(
        'UserProfile', related_name='received_messages', verbose_name=_(u"Получатель"))
    parent_msg = models.ForeignKey(
        'self', related_name='next_messages', null=True, blank=True, verbose_name=_(u"Parent message"))
    sent_at = models.DateTimeField(_(u"Отправленно"), auto_now_add=True)
    read_at = models.DateTimeField(_(u"read at"), null=True, blank=True)
    replied_at = models.DateTimeField(_(u"replied at"), null=True, blank=True)
    sender_deleted_at = models.DateTimeField(_(u"Sender deleted at"), null=True, blank=True)
    recipient_deleted_at = models.DateTimeField(_(u"Recipient deleted at"), null=True, blank=True)

    objects = MessageManager()

    def new(self):
        """returns whether the recipient has read the message or not"""
        if self.read_at is not None:
            return False
        return True

    def replied(self):
        """returns whether the recipient has written a reply to this message"""
        if self.replied_at is not None:
            return True
        return False

    def __unicode__(self):
        return self.subject

    class Meta:
        ordering = ['-sent_at']
        verbose_name = _(u"Личное сообщение")
        verbose_name_plural = _(u"Личные сообщения")


def inbox_count_for(user):
    """
    returns the number of unread messages for the given user but does not
    mark them seen
    """
    return Message.objects.filter(recipient=user, read_at__isnull=True, recipient_deleted_at__isnull=True).count()

comments/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic

from cabinet.models import UserProfile as User
from core.utils import UCrypto, mat_validator


class Comment(models.Model):

    class Meta:
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'
        get_latest_by = 'created'

    ip = models.GenericIPAddressField(u'IP address', unpack_ipv4=True, blank=True, null=True)
    created = models.DateTimeField(u'дата создания', auto_now_add=True)
    hidden = models.BooleanField(u'скрыть', default=False, help_text=u'Будет скрыто, если отмечено')

    user = models.ForeignKey(User, verbose_name=u'Пользователь')
    text = models.TextField(u'сообщение', validators=[mat_validator])

    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def get_name(self):
        return self.user.get_full_name()

    def get_date(self):
        return self.created.strftime('%d %B %Y %H:%M')

    def __unicode__(self):
        return self.get_date()

search/models.py
from django.db import models

# Create your models here.

search/forms.py
# -*- coding:utf-8 -*-
from django import forms
from catalog.models import Advert


class SearchForm(forms.Form):
    query = forms.CharField(required=True)

search/views.py
# -*- coding:utf-8 -*-
from django.shortcuts import render
from django.template import RequestContext

from core.utils import paginate_objects
from catalog.index import complete_indexer as indexer
from search.forms import SearchForm


def search(request):

    page = request.GET.get('page')
    results = []
    form = SearchForm(request.GET or None)

    if request.GET and form.is_valid():
        query = ' OR '.join(map(lambda x: x.strip(',').strip(),
                                form.cleaned_data['query'].split(' ')),
                            )
        results = indexer.search(query).prefetch()

    results = precache_foreignkey(paginate_objects(results, 20, page=page),
                                  'cover')

    return render(request, 'search.html', {'results': results, 'form': form})


def precache_foreignkey(items, field):
    '''Return items with cached foreignkey objects '''
    field_id = field + '_id'
    ids, model = list(), None
    for obj in items:
        try:
            ids.append(getattr(obj.instance, field_id))
        except AttributeError:
            pass
        if model is None:
            model = obj.instance._meta.get_field_by_name(field)[0].rel.to
    if model is not None:
        cache = model.objects.in_bulk(ids)
        for obj in items:
            try:
                setattr(obj.instance,
                        field,
                        cache.get(getattr(obj.instance, field_id)))
            except AttributeError:
                pass
    return items

templates/ad.html
{% extends "base.html" %}
{% load i18n staticfiles thumbnail comments_tags core_tags cache %}

{% block title %}{{ advert.title }}{% endblock %}

{% block javascript %}
    <script src="{% static 'js/jquery.wysibb.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'theme/default/wbbtheme.css' %}" type="text/css" />

    <script>
        // $(document).ready(function() {
        // var wbbOpt = {
        // buttons: "bold,italic,underline,|,img,link,|,code,quote"
        // }
        // $("#id_text").wysibb(wbbOpt);
        // });
    </script>

{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'catalog:detail' advert.category.catalog.slug %}">{{ advert.category.catalog.title }}</a>
    <a href="{% url 'catalog:category_detail' advert.category.slug %}">{{ advert.category.title }}</a>
    <a href="{% url 'catalog:category_detail' advert.category.slug %}?advtype={{ advert.type }}">{{ advert.get_type_display }}</a>
    <a href="{% url 'catalog:advert_detail' advert.pk %}">{{ advert.title }}</a>
{% endblock breadcrumbs %}

{% block content %}
<section class="container">
    <div class="content center">
        <h1>
            <span class="sell">{{ advert.get_type_display|upper }}</span>
            {{ advert.title }}
            <span class="price">{{ advert.get_price }}</span>
        </h1>
        {% ifequal advert.user_id request.user.id %}
        <p class="ad_controls">
            <a href="{% url 'catalog:advert_notactual' advert.pk %}" class="del">Не актуально</a>
            <a href="{% url 'catalog:advert_edit' advert.pk %}" class="del">Редактировать</a>
        </p>
        {% endifequal %}
        <div class="ad_main_img">
        {% with advert.advertimage_set.all as images %}

            {% for img in images %}
                {% if forloop.first %}
                    <div class="small_img">
                {% endif %}
                    {% thumbnail img.image "80x60" crop='center' as im %}
                        <a href="{{ img.image.url }}">
                            <img src="{{ im.url }}">
                        </a>
                    {% endthumbnail %}

                {% with images|length as len_images %}
                    {% if len_images < 4 %}
                        {% if forloop.counter|divisibleby:len_images %}
                            </div>
                            {% for img in images %}
                                <a
                                data-fancybox-group="gallery"
                                href="{{ img.image.url }}"
                                {% ifnotequal advert.cover_id img.id %}
                                    class="visible"
                                {% endifnotequal %}
                                >
                                    {% thumbnail img.image "480x323" as im %}
                                        <img
                                        style="margin:{{ im|margin:"480x323" }}"
                                        src="{{ im.url }}"
                                        >
                                    {% endthumbnail %}
                                </a>
                            {% endfor %}
                            <div class="small_img">
                        {% endif %}
                    {% else %}
                        {% if forloop.counter == 4 %}
                            </div>
                            {% for img in images %}
                                {% if img.image %}
                                    <a data-fancybox-group="gallery" href="{{ img.image.url }}" {% ifnotequal advert.cover_id img.id %}class="visible"{% endifnotequal %}>
                                        {% thumbnail img.image "480x323" as im %}
                                            <img
                                                    style="margin:{{ im|margin:"480x323" }}"
                                                    src="{{ im.url }}"
                                                    >
                                        {% endthumbnail %}
                                    </a>
                                {% endif %}
                            {% endfor %}
                            <div class="small_img">
                        {% endif %}
                    {% endif %}
                {% endwith %}

                {% if forloop.last %}
                    </div>
                {% endif %}
            {% empty %}
                <p>Изображения отутствуют.</p>
            {% endfor %}

        {% endwith %}
        </div>

        <h3>Описание</h3>
        <div class="ad_desc">
            <p>{{ advert.description|safe|default:"<p>Описание отсутствует.</p>" }}</p>
            <p>{{ advert.user.by_line }}</p>
        </div>

        {% if comment_form %}
            {% render_exist_comments_form form=comment_form _next=request.GET.next %}
        {% else %}
            {% render_text_comments_form advert request.user _next=request.path %}
        {% endif %}

        {% render_comments_list advert request.GET.page %}
    </div>

    <aside class="right">
        {% get_latest %}
    </aside>
</section>
{% endblock content %}

templates/adverts.html
{% extends "cabinet.html" %}
{% load i18n staticfiles thumbnail cache registration_tags core_tags %}

{% block title %}Объявления{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'cabinet:adverts' %}">Мои объявления</a>
{% endblock breadcrumbs %}

{% block cabinet_content %}
    <div class="content center">
        <h3>Объявления</h3>

        {% get_paginator 'adverts' %}

        <div class="tape_ads">
            {% for advert in adverts %}
                <div class="ad">
                    {% if not advert.actual %}
                        <div class="not_actual">Не актуально</div>
                    {% endif %}
                    {% thumbnail advert.get_cover_image "100x80" crop="center" as im %}
                        <img class="my_event_photo" src="{{ im.url }}" alt="{{ event.title }}">
                    {% empty %}
                        <img class="my_event_photo" src="{% static 'images/nophoto.jpg' %}" alt="{{ advert.title }}">
                    {% endthumbnail %}
                    <div class="ad_info">
                        <div class="ad_price">
                            {{ advert.price }}
                            ({{ advert.currency }})
                            <p class="comments"><span></span>22
                            </p>
                        </div>
                        <header>
                            <span class="type{{ advert.type }}">{{ advert.get_type_display }}</span>
                            <a href="{% url 'catalog:advert_detail' advert.pk %}">{{ advert.title|truncatechars:35 }}</a>
                        </header>
                        <p class="cabinet_ad_short_desc">
                            {{ advert.description|truncatechars:170|safe|striptags|default:'Описание отсутствует.' }}
                        </p>
                        <div class="nav_button">
                            <a href="{% url 'catalog:advert_delete' pk=advert.pk %}" class="btn ptomt_delete">{% trans 'Удалить' %}</a>
                            <a href="{% url 'catalog:advert_detail' pk=advert.pk %}" class="btn">{% trans 'Просмотр' %}</a>
                            {% if advert.actual %}
                                <a href="{% url 'catalog:advert_edit' advert.pk %}" class="btn">редактировать</a>
                            {% endif %}
                        </div>
                        <p class="ad_city">
                            {% if advert.region %}{{ advert.region.title_ru }}{% endif %}{% if advert.city %}, {{ advert.city.title_ru }}{% endif %}
                            <span class="when">{{ advert.changed_last|timesince|bring_space:',' }} назад</span>
                        </p>
                    </div>
                    <div class="clear"></div>
                </div>
            {% empty %}
                Нет ни одного объявления.
            {% endfor %}
        </div>

        {% get_paginator 'adverts' %}

    </div>
{% endblock cabinet_content %}

templates/catalog.html
{% extends "base.html" %}
{% load staticfiles thumbnail core_tags %}

{% block title %}
    {{ catalog.title }}
{% endblock title %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'catalog:detail' catalog.slug %}">{{ catalog.title }}</a>
{% endblock breadcrumbs %}

{% block center %}
<div class="content">
    {% for cat in categories %}
        {% if cat.adverts %}
            <div class="category_block">
                <header><a href="{% url 'catalog:category_detail' cat.slug %}">{{ cat.title }}</a></header>
                <div>
                {% for item in cat.adverts %}
                    {% if forloop.first or not forloop.counter|divisibleby:'2' %}
                        <div class="column">
                    {% endif %}
                    <div class="item">
                        <div class="item_img">
                            <a href="{% url 'catalog:advert_detail' advert.pk %}" class="pull-left">
                                <div class="cycle-slideshow"
                                     data-cycle-pause-on-hover="true"
                                     data-cycle-speed="{{ site_settings.time_slider }}"
                                        >
                                    {% for image in advert.advertimage_set.all %}
                                        {#                    {{ event.self.eventimage_set. }}#}
                                        {% thumbnail image.image "80x65" crop='center' as im %}
                                            <img src="{{ im.url }}" alt="" {% if forloop.counter != 1 %} style='display: none;'{% endif %}>
                                        {% endthumbnail %}
                                    {% empty %}
                                        <img src="{% static "images/ad/1.jpg" %}" alt="">
                                    {% endfor %}
                                </div>
                            </a>
                        </div>
                        <div class="item_desc">
                            <p class="desc">
                                <a href="{% url 'catalog:advert_detail' item.pk %}">
                                    {{ item.title|truncatechars:19 }}
                                </a>
                            </p>
                            <p class="price">
                                {{ item.get_price }}
                            </p>
                            <p>{{ item.type|get_advert_type_display }}</p>
                        </div>
                        <div class="clr"></div>
                    </div>
                    {{ forloop.counter }}
                    {% if forloop.last or forloop.counter|divisibleby:'2' %}
                        </div>
                    {% endif %}
                {% endfor %}
                </div>
            </div>
        {% endif %}
    {% endfor %}
</div>
{% endblock center %}

templates/drafts.html
{% extends "cabinet.html" %}
{% load i18n staticfiles thumbnail cache registration_tags core_tags %}

{% block title %}Черновики{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'cabinet:drafts' %}">Черновики</a>
{% endblock breadcrumbs %}

{% block cabinet_content %}
<div class="content center">
    <h3>Черновики</h3>

    {% get_paginator 'adverts' %}

    <div class="tape_ads">
    {% for advert in adverts %}
        <div class="ad">
            {% thumbnail advert.cover.image "100x80" crop='center' as im %}
                <img src="{{ im.url }}">
            {% empty %}
                <img src="{% static "images/nophoto.jpg" %}">
            {% endthumbnail %}
            <div class="ad_info">
                <div class="ad_price">
                    {% if advert.price %}
                        {{ advert.price }}
                    {% endif %}
                    {% if advert.currency %}
                        ({{ advert.currency }})
                    {% endif %}
                    <p class="control">
                        <a href="{% url 'cabinet:draft_delete' advert.pk %}"  class="del">удалить</a>
                        <br>
                        <a href="{% url 'cabinet:draft_edit' advert.pk %}" class="del">редактировать</a>
                    </p>
                </div>
                <header>
                        <span class="type{{ advert.type }}">
                        {% if advert.type %}
                            {{ advert.get_type_display }}
                        {% else %}
                            -
                        {% endif %}
                        </span>
                    <a href="{% url 'cabinet:draft_edit' advert.pk %}">
                        {% if advert.title %}
                            {{ advert.title|truncatechars:35 }}
                        {% else %}
                            {% trans "<Заголовок отсутствует>" %}
                        {% endif %}
                    </a>
                </header>
                <p class="cabinet_ad_short_desc">
                    {{ advert.description|striptags|truncatechars:170|safe|default:'Описание отсутствует.' }}
                </p>
                <p class="ad_city">
                    {% if advert.region %}{{ advert.region.title_ru }}{% endif %}{% if advert.city %}, {{ advert.city.title_ru }}{% endif %}
                    <span class="when">{{ advert.changed_last|timesince|bring_space:',' }} назад</span>
                </p>
            </div>
            <div class="clear"></div>
        </div>
    {% empty %}
        Нет ни одного черновика.
    {% endfor %}
    </div>

    {% get_paginator 'adverts' %}

</div>
{% endblock cabinet_content %}

templates/my_messages.html
{% extends "cabinet.html" %}
{% load i18n staticfiles thumbnail cache registration_tags core_tags %}

{% block title %}{% trans 'Сообщения' %}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <a href="{% url 'cabinet:messages' %}">{% trans 'Сообщения' %}</a>
{% endblock breadcrumbs %}

{% block cabinet_content %}
    <div class="content center">
        <div class="clearfix">
            <h3 class="left">{% trans 'Диалоги' %}</h3>
            <a href="{% url 'cabinet:message_new' %}" class="btn rightt">{% trans 'Написать сообщение' %}</a>
        </div>
            {% get_paginator 'page_obj' %}
        <div class="message_list dialog-list">
            {% for message in messages_list %}
                <a href="{% url 'cabinet:dialog' message.user.username %}">
                    <div class="message {% if message.is_new %}new{% endif %}">
                        <div class="item_img">
                            {% thumbnail message.user.avatar "80x65" crop='center' as im %}
                                <img src="{{ im.url }}" alt="">
                            {% empty %}
                                <img width="80" height="65" src="{% static "images/nophoto.jpg" %}">
                            {% endthumbnail %}
                            <div class="pull-right">
                                <p>{{ message.user.username }}</p>
                                <p class="time-message">{{ message.last_message.sent_at|date:'d M Y в H:i' }}</p>
                                <p class="btn delete_m ptomt_delete" data-url="{% url 'cabinet:dialog_delete' message.user.username %}">{% trans 'Удалить' %}</p>
                            </div>
                        </div>
                        <div class="item_desc">
                            <p class="desc">
                                Тема: {{ message.last_message.subject }}
                            </p>
                            <p>{{ message.last_message.body|truncatechars:100 }}</p>
                            <br/><br/>
                        </div>
                    </div>
                </a>
            {% empty %}
                {% trans 'нет ни одного сообщения' %}
            {% endfor %}
        </div>
            {% get_paginator 'page_obj' %}
    </div>
{% endblock cabinet_content %}